### ISSUE TITLE
Bind this repository (or a branch) to runtime-spec releases

### ISSUE THREAD

**Issue by wking** [opencontainers/ocitools#108]
This is somewhat related to #16 (where [a comment][1] sounded like “we'll get serious once we get to 1.0”), and #69 (where I argue that [we should not float with runC][2]).  But concretely, I am unable to test ccon with the current ocitools.  For one, my command-line API is different (I expect `RUNTIME start --id $CONTAINER_ID`, while runC seems to prefer `RUNTIME start $CONTAINER_ID`).  But once I've patched around that:

    ocitools$ git diff -U0
    diff --git a/test_runtime.sh b/test_runtime.sh
    index da3f026..d498ae8 100755
    --- a/test_runtime.sh
    +++ b/test_runtime.sh
    @@ -84 +84 @@ popd > /dev/null
    -TESTCMD="${RUNTIME} start $(uuidgen)"
    +TESTCMD="${RUNTIME} start --id $(uuidgen)"

I still cannot run the tests, because they're based on an unreleased 0.6.0-dev version of the spec:

    ocitools$ ./test_runtime.sh -l debug -r ccon-oci
    -----------------------------------------------------------------------------------
    VALIDATING RUNTIME: ccon-oci
    -----------------------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/wking/bin/ccon-oci", line 578, in <module>
        main()
      File "/home/wking/bin/ccon-oci", line 574, in main
        args.func(**kwargs)
      File "/home/wking/bin/ccon-oci", line 442, in start
        config_state = _load_config(bundle=bundle, id=id)
      File "/home/wking/bin/ccon-oci", line 421, in _load_config
        version = _get_version(config=config)
      File "/home/wking/bin/ccon-oci", line 64, in _get_version
        'unsupported OCI-spec version: {}'.format(version))
    NotImplementedError: unsupported OCI-spec version: 0.6.0-dev
    Runtime ccon-oci failed validation

Is there a branching plan for supporting per-version testing?  For example, we might want to start a v1.0 branch to track the v1.0 release series while `master` continues on with any changes destined for v1.1 / v2.0, etc.  Then the v1.0 branch could generate (at the moment) 1.0.0-rc1 specs that ccon-oci understands.

[1]: https://github.com/opencontainers/ocitools/issues/16#issuecomment-174609225
[2]: https://github.com/opencontainers/ocitools/issues/69#issuecomment-223844232

**Comment by wking** [comment]
After more discussion in #140, we got [a v1.0.0.rc1 branch last month][1].  So far most work has gone into master with frequent backport cherry-picks and the odd PR targeting v1.0.0.rc1.  This works well enough for me, so I'm closing this issue.

[1]: https://github.com/opencontainers/ocitools/pull/140#issuecomment-234615096
